import {CONFIG} from './config.js';
import {PROGRAMME_LABELS} from './programme-labels.js';
const $=id=>document.getElementById(id);
const sections=[['rna','RNA programmes'],['rna_protein','RNA–protein'],['ptm','Protein & PTM'],['simulation','Simulations'],['reference','Deconvolution & PCA'],['signatures','Gene signatures'],['single_cell','Single-cell reference']];
const state={catalog:[],section:'rna',dataset:null,rows:[],filtered:[],facets:{},page:0,view:'plot',mode:'biology',version:0,figure:null,worker:null,plotId:0};
const cache=new Map();
const number=new Intl.NumberFormat('en',{maximumSignificantDigits:5});
const human=s=>String(s).replaceAll('_',' ');
function programmeLabel(r){const key=r.feature||r.programme;const names=PROGRAMME_LABELS[key];return names?names.map(n=>human(n.replace(/_Signature$/,''))).join(' / ')+' ['+key.slice(-6)+']':r.label||r.feature||r.programme;}
function searchable(r){return Object.values(r).concat(programmeLabel(r)||'');}
function el(tag,text,attrs={}){const e=document.createElement(tag);if(text!==undefined)e.textContent=text;for(const[k,v]of Object.entries(attrs))e.setAttribute(k,v);return e;}
function status(message,error=false){$('status').textContent=message;$('status').classList.toggle('error',error);}
async function api(table,query){const url=new URL(CONFIG.url+'/rest/v1/'+table);for(const[k,v]of Object.entries(query))url.searchParams.set(k,v);const res=await fetch(url,{headers:{apikey:CONFIG.key},signal:AbortSignal.timeout(30000)});if(!res.ok)throw Error('Results could not be loaded ('+res.status+'). Please try again.');return res.json();}
function options(select,values,selected){select.replaceChildren();for(const [value,label]of values){const o=el('option',label,{value});select.append(o);}if(selected!==undefined)select.value=selected;}
function safeValue(v){if(v===null||v===undefined||v==='')return '—';if(typeof v==='number')return number.format(v);if(typeof v==='object')return JSON.stringify(v);return String(v);}
function save(content,name,type){const url=URL.createObjectURL(content instanceof Blob?content:new Blob([content],{type}));const a=el('a',undefined,{href:url,download:name});document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function csvCell(v){let s=v==null?'':typeof v==='object'?JSON.stringify(v):String(v);if(/^[=+@\t\r]/.test(s)||(/^-.+/.test(s)&&!Number.isFinite(Number(s))))s="'"+s;return '"'+s.replaceAll('"','""')+'"';}
function filteredCSV(rows){const cols=[...new Set(rows.flatMap(Object.keys))];return [cols.map(csvCell).join(','),...rows.map(r=>cols.map(c=>csvCell(r[c])).join(','))].join('\r\n');}
function clearFigure(){state.plotId++;state.figure=null;$('svg').disabled=$('png').disabled=true;$('plot-caption').textContent='';$('figure-container').replaceChildren(el('div','Choose a figure type and draw the current selection.',{class:'plot-empty'}));}
const runLabel={immune_coarse:'Coarse immune',immune_fine:'Fine immune',nonimmune:'Non-immune'};
const collectionLabel=d=>{const part=d.id.split('/')[1];return ({effects:'Effect estimates',run_diagnostics:'Sampling overview',diagnostic_families:'R-hat & ESS by parameter family',diagnostic_family_summary:'R-hat & ESS by parameter family',ppc_domain_checks:'Predictive checks · domains',ppc_v2_domain_checks:'Predictive checks · domains',ppc_feature_checks:'Predictive checks · features',ppc_v2_feature_checks:'Predictive checks · features',fit_status:'Sampling checks · all fits',run_status:'Sampling checks · all fits',predictive_checks:'Posterior predictive checks',all_predictive_checks:'Posterior predictive checks'})[part]||d.title;};
function syncRunControls(d){if(d?.section==='rna'){const categorical=d.run_key.startsWith('categorical_');$('bmi-model').value=categorical?'categorical':'continuous';$('compartment').value=d.run_key.replace('categorical_','');}}
function availableCollections(section){return state.catalog.filter(d=>d.section===section).filter(d=>{if(state.mode==='advanced')return d.title.toLowerCase().includes($('collection-search').value.trim().toLowerCase());if(state.mode==='biology'&&d.kind!=='effects')return false;if(state.mode==='reliability'&&d.kind!=='diagnostics')return false;if(section==='rna'){const run=($('bmi-model').value==='categorical'?'categorical_':'')+$('compartment').value;return d.run_key===run;}return true;});}
function changeSection(section,preferred){
 if(['simulation','reference','signatures','single_cell'].includes(section)&&state.mode!=='advanced'){state.mode='advanced';updateModeUI();}
 state.section=section;for(const b of $('sections').children)b.setAttribute('aria-selected',b.dataset.section===section);
 $('rna-navigation').hidden=state.mode==='advanced'||section!=='rna';
 const choices=availableCollections(section);const defaultId=state.mode==='reliability'?(choices.find(d=>/run_diagnostics|fit_status|run_status/.test(d.id))?.id):choices.find(d=>d.kind==='effects')?.id;
 options($('dataset'),choices.map(d=>[d.id,state.mode==='advanced'?d.title:collectionLabel(d)]),choices.some(d=>d.id===preferred)?preferred:defaultId||choices[0]?.id);
 $('dataset').hidden=state.mode==='biology'&&choices.length===1;$('dataset-label').hidden=$('dataset').hidden;
 if(!choices.length){state.version++;state.dataset=null;$('search').disabled=true;$('reset').disabled=true;$('prev').disabled=true;$('next').disabled=true;state.rows=[];state.filtered=[];clearFigure();$('dataset-title').textContent='No matching collections';$('dataset-description').textContent='Clear the collection search to see the full archive.';$('download').disabled=true;$('download-json').hidden=true;$('diagnostic-panel').hidden=true;$('tbody').replaceChildren();$('facets').replaceChildren();$('extra-facets').replaceChildren();$('result-count').textContent='';$('draw').disabled=true;status('');return;}
 loadDataset();
}
function updateModeUI(){for(const b of document.querySelectorAll('[data-mode]'))b.setAttribute('aria-selected',b.dataset.mode===state.mode);$('collection-search-label').hidden=state.mode!=='advanced';$('extra-options').open=state.mode==='advanced';$('mode-help').textContent=state.mode==='biology'?'Start with a data layer and compartment. Primary models are selected by default; sensitivity analyses remain under More options.':state.mode==='reliability'?'Inspect sampling quality and predictive checks. Failed fits remain visible here. Summary diagnostics do not replace chain traces.':'All '+state.catalog.length+' collections: effect estimates, diagnostics, simulations, reference data and sensitivity analyses.';}
function setMode(mode){state.mode=mode;$('collection-search').value='';syncRunControls(state.dataset);updateModeUI();changeSection(state.section,state.dataset?.id);}
async function loadDataset(){
 const version=++state.version;state.dataset=state.catalog.find(d=>d.id===$('dataset').value);if(!state.dataset)return;
 const d=state.dataset;$('download-json').hidden=d.kind!=='signatures';$('download-json').disabled=true;$('search').disabled=false;$('reset').disabled=false;state.rows=[];state.filtered=[];state.facets={};state.page=0;clearFigure();$('search').value='';$('include-failed').checked=false;$('download').disabled=true;$('facets').replaceChildren();$('extra-facets').replaceChildren();$('diagnostic-panel').hidden=true;$('draw').disabled=true;$('tbody').replaceChildren();$('thead').replaceChildren();
 $('dataset-title').textContent=state.mode==='advanced'?d.title:(d.section==='rna'?runLabel[d.run_key.replace('categorical_','')]:sections.find(s=>s[0]===d.section)[1])+' · '+collectionLabel(d);$('dataset-description').textContent=d.description;$('section-label').textContent=sections.find(s=>s[0]===d.section)[1];$('notice').hidden=!d.provisional;$('notice').textContent=d.provisional?'Provisional analysis: interpret these fine-immune categorical results with the diagnostic evidence.':'';
 status('Loading '+number.format(d.row_count)+' result rows…');history.replaceState(null,'','#dataset='+encodeURIComponent(d.id)+'&mode='+state.mode);
 try{
  let rows=cache.get(d.id);
  if(!rows){rows=[];for(let offset=0;offset<d.row_count;offset+=1000){const page=await api('atlas_web_rows',{select:'row_number,data',dataset_id:'eq.'+d.id,order:'row_number.asc',limit:1000,offset});if(version!==state.version)return;if(!page.length)throw Error('Incomplete data response. Please retry.');rows.push(...page.map(x=>x.data));status('Loading results: '+number.format(rows.length)+' / '+number.format(d.row_count));}if(rows.length!==d.row_count)throw Error('The collection changed during loading. Please reload.');cache.set(d.id,rows);}
  if(version!==state.version)return;state.rows=rows;$('include-failed').checked=d.kind==='diagnostics';buildFacets();applyFilters();view(state.mode==='biology'?'plot':'table');$('view-plot').hidden=state.mode==='reliability';status('');
 }catch(e){if(version===state.version){status(e.message,true);$('result-count').textContent='';}}
}
const facetFields=['entity_level','variant','component','contrast','units','cell_type','assay','geometry','kind','rule','scenario','check','domain','parameter_family','compartment','analysis_set','PC','CellType','reference','resolution','scope','endpoint','cap'];
function buildFacets(preserve=false){
 const previous=preserve?{...state.facets}:{};state.facets={};
 $('facets').replaceChildren();$('extra-facets').replaceChildren();for(const key of facetFields){const eligible=state.rows.filter(r=>Object.entries(state.facets).every(([k,v])=>!v||String(r[k])===v));const values=[...new Set(eligible.map(r=>r[key]).filter(v=>v!==null&&v!==undefined&&v!==''))].sort();if(values.length<2||values.length>150)continue;
 const mandatory=(state.dataset.kind==='scree'&&['compartment','analysis_set'].includes(key))||(state.dataset.kind==='contributions'&&['compartment','analysis_set','PC'].includes(key))||(state.dataset.kind==='annotation'&&['reference','resolution'].includes(key))||(state.dataset.kind==='effects'&&['entity_level','variant','component','contrast','units'].includes(key))||(state.mode==='reliability'&&['variant','check','domain'].includes(key));
 let initial=previous[key]&&values.map(String).includes(previous[key])?previous[key]:mandatory?(values.includes('primary')?'primary':values.includes('feature')?'feature':values[0]):'';
 const fieldNames={variant:'Analysis version',component:'Quantity to compare',cell_type:'Cell type',entity_level:'Feature level',contrast:'BMI contrast',units:'Measurement scale',assay:'Assay'};const label=el('label',fieldNames[key]||human(key));const select=el('select',undefined,{'aria-label':fieldNames[key]||human(key)});options(select,[...(!mandatory?[['','All']]:[]),...values.map(v=>[String(v),human(v)])],String(initial));state.facets[key]=String(initial);select.dataset.key=key;select.onchange=()=>{state.facets[key]=select.value;state.page=0;buildFacets(true);applyFilters();};label.append(select);const extra=state.mode!=='advanced'&&['variant','entity_level','units','parameter_family'].includes(key);$(extra?'extra-facets':'facets').append(label);
 }
 $('include-failed').closest('label').hidden=state.dataset.kind==='diagnostics'||!state.rows.some(r=>r.numerical_checks_pass!==undefined);$('extra-options').hidden=!$('extra-facets').children.length;
}
function applyFilters(){
 const term=$('search').value.trim().toLowerCase();state.filtered=state.rows.filter(r=>Object.entries(state.facets).every(([k,v])=>!v||String(r[k])===v)&&(state.dataset.kind==='diagnostics'||$('include-failed').checked||![false,'False','false'].includes(r.numerical_checks_pass))&&(!term||searchable(r).some(v=>v!=null&&String(v).toLowerCase().includes(term))));
 state.page=0;clearFigure();$('download').disabled=!state.filtered.length;$('download-json').disabled=!state.filtered.length;$('result-count').textContent=number.format(state.filtered.length)+' / '+number.format(state.rows.length)+' rows';drawTable();setupPlot();renderDiagnostics();$('selection-summary').textContent=[state.dataset.kind==='effects'?'Pointwise 95% intervals':'Saved analysis summaries',...['variant','component','contrast','units'].map(k=>state.facets[k]?human(state.facets[k]):'').filter(Boolean)].join(' · ');
}
function drawTable(){
 const rows=state.filtered;const keys=[...new Set(rows.flatMap(Object.keys))];const first=state.dataset.kind==='effects'?['label','cell_type','gene','estimate','hdi_lower','hdi_upper','units','contrast','component','variant','numerical_checks_pass']:[];const cols=state.mode==='biology'&&state.dataset.kind==='effects'?['label','cell_type','gene','estimate','hdi_lower','hdi_upper','units'].filter(k=>keys.includes(k)):[...first.filter(k=>keys.includes(k)),...keys.filter(k=>!first.includes(k))];
 const tr=el('tr');for(const c of cols)tr.append(el('th',human(c),{scope:'col'}));$('thead').replaceChildren(tr);$('tbody').replaceChildren();
 for(const row of rows.slice(state.page*25,(state.page+1)*25)){const tr=el('tr');for(const c of cols){const td=el('td',safeValue(c==='label'&&state.mode!=='advanced'?programmeLabel(row):row[c]));if(c==='numerical_checks_pass'&&[false,'False','false'].includes(row[c]))td.className='flag';tr.append(td);}$('tbody').append(tr);}
 if(!rows.length){const tr=el('tr');tr.append(el('td','No results match these filters. Try resetting the filters.'));$('tbody').append(tr);}
 const pages=Math.max(1,Math.ceil(rows.length/25));$('page-label').textContent=`Page ${state.page+1} of ${pages}`;$('prev').disabled=state.page===0;$('next').disabled=state.page>=pages-1;
}
function setupPlot(){
 const kind=state.dataset.kind;const old=$('plot-type').value;const types=kind==='effects'?[['forest','Effect intervals'],['heatmap','Original-style heatmap']]:kind==='coverage'?[['coverage','Coverage counts']]:kind==='scree'?[['scree','PCA explained variance']]:kind==='contributions'?[['contributions','Cell-type contribution to PC']]:kind==='annotation'?[['annotation','Annotation counts']]:[['histogram','Distribution'],['scatter','Scatterplot']];options($('plot-type'),types,types.some(t=>t[0]===old)?old:types[0][0]);
 const cols=[...new Set(state.filtered.flatMap(Object.keys))].filter(k=>state.filtered.some(r=>r[k]!==''&&r[k]!=null&&typeof r[k]!=='boolean'&&Number.isFinite(Number(r[k]))));options($('plot-x'),cols.map(c=>[c,human(c)]));options($('plot-y'),cols.map(c=>[c,human(c)]),cols[1]||cols[0]);plotControls();
}
function plotControls(){const t=$('plot-type').value;$('x-wrap').hidden=!['scatter','histogram'].includes(t);$('y-wrap').hidden=t!=='scatter';$('plot-limit').parentElement.hidden=!['forest','heatmap'].includes(t);$('draw').disabled=!state.filtered.length;}
function view(which){state.view=which;$('table-panel').hidden=which!=='table';$('plot-panel').hidden=which!=='plot';$('view-table').setAttribute('aria-selected',which==='table');$('view-plot').setAttribute('aria-selected',which==='plot');}
let busy=false;
async function drawPlot(){
 if(busy)return;busy=true;$('draw').disabled=true;const id=++state.plotId;
 status('Preparing the figure…');
 if(!state.worker){state.worker=new Worker('./plot-worker.js?v=20261003-module',{type:'module'});state.worker.onmessage=({data})=>{if(data.status){if(busy)status(data.status);return;}busy=false;$('draw').disabled=!state.filtered.length;if(data.id!==state.plotId)return;if(data.error){status(data.error.split('\n').filter(Boolean).slice(-1)[0],true);return;}state.figure=data.result;const img=el('img',undefined,{alt:state.dataset.title+' — '+$('plot-type').selectedOptions[0].text});const url=URL.createObjectURL(new Blob([data.result.svg],{type:'image/svg+xml'}));img.onload=()=>URL.revokeObjectURL(url);img.src=url;$('figure-container').replaceChildren(img);$('plot-caption').textContent=data.result.caption;$('svg').disabled=$('png').disabled=false;status('Figure ready.');};state.worker.onerror=()=>{busy=false;$('draw').disabled=false;status('The plotting worker could not start. Reload the page and try again.',true);state.worker.terminate();state.worker=null;};}
 state.worker.postMessage({id,request:{rows:state.filtered.map(r=>r.feature&&PROGRAMME_LABELS[r.feature]?{...r,label:programmeLabel(r)}:r),type:$('plot-type').value,x:$('plot-x').value,y:$('plot-y').value,limit:Number($('plot-limit').value),title:state.dataset.title}});
}

const diagnosticSpecs=[
 {id:'rhat',label:'R-hat · maximum',keys:['max_all_parameter_rhat','maximum_rhat','max_rhat'],higherBad:true,reference:1.01,note:'Each point is the reported maximum R-hat for one parameter family or fit. Values near 1 indicate agreement between chains. The dashed line is 1.01; this is a diagnostic reference, not an overall model-validity verdict.'},
 {id:'bulk',label:'Bulk ESS · minimum',keys:['min_all_parameter_ess_bulk','minimum_bulk_ess','min_ess_bulk'],higherBad:false,note:'Each point is the reported minimum bulk effective sample size for one family or fit, not a chain or patient count. It describes information available for central posterior estimates; larger values generally mean better Monte Carlo precision.'},
 {id:'tail',label:'Tail ESS · minimum',keys:['min_all_parameter_ess_tail','minimum_tail_ess','min_ess_tail'],higherBad:false,note:'Each point is the reported minimum tail effective sample size for one family or fit. Tail ESS concerns precision in the posterior tails and should be reviewed separately from bulk ESS.'},
 {id:'bfmi',label:'BFMI · minimum across chains',keys:['min_bfmi'],higherBad:false,note:'Minimum reported BFMI across chains. This summarizes energy exploration; it does not show individual chain trajectories.'},
 {id:'divergences',label:'Divergences · count',keys:['divergences'],higherBad:true,note:'Recorded divergence counts for each saved fit. Zero is desirable. No percentage is inferred when the required draw totals are unavailable.'},
 {id:'ppc',label:'Observed versus predictive interval',keys:['observed_draw_median','observed_count','observed_median'],higherBad:true,note:'Observed summaries (magenta points) compared with the saved predictive interval (blue lines). Different predictive statistics must be viewed separately. These checks assess model fit, not convergence or calibrated discovery probabilities.'},
 {id:'tail-rate',label:'Predictive tail outside rate',keys:['tail_outside_rate'],higherBad:true,note:'Saved predictive tail outside rate per feature. This is a model-check summary, not an MCMC diagnostic or a discovery probability.'},
 {id:'coverage',label:'Predictive 90% interval coverage',keys:['predictive_90pct_coverage'],higherBad:false,reference:.9,note:'Saved predictive coverage per feature, with a 0.90 reference. Coverage and MCMC convergence answer different questions.'}
];
const diagnosticNumber=(r,keys)=>{for(const k of keys){const v=r[k];if(v!==null&&v!==undefined&&v!==''&&Number.isFinite(Number(v)))return Number(v);}return null;};
const isFalse=v=>v===false||v==='False'||v==='false';
const isTrue=v=>v===true||v==='True'||v==='true';
let activeDiagnosticSpecs=[],diagnosticSVG='';
function renderDiagnostics(){
 const visible=state.dataset?.kind==='diagnostics';$('diagnostic-panel').hidden=!visible;if(!visible)return;
 const rows=state.filtered;$('diagnostic-cards').replaceChildren();
 const card=(label,value,review=false)=>{const box=el('div',undefined,{class:'metric-card'+(review?' review':'')});box.append(el('strong',value),el('span',label));$('diagnostic-cards').append(box);};
 card('Saved summary rows',number.format(rows.length));
 if(!rows.length){$('diagnostic-explanation').textContent='No diagnostic rows match the filters.';$('diagnostic-chart').replaceChildren();$('diagnostic-metric-label').hidden=true;$('diagnostic-svg').hidden=true;return;}
 const flags=rows.filter(r=>r.numerical_checks_pass!==undefined||r.gate_pass!==undefined||r.publication_convergence_pass!==undefined);
 if(flags.length){const failed=flags.filter(r=>isFalse(r.numerical_checks_pass)||isFalse(r.gate_pass)||isFalse(r.publication_convergence_pass)).length;card('Fits failing a recorded numerical gate',failed+' / '+flags.length,failed>0);}
 if(rows.length===1){const r=rows[0];const chains=diagnosticNumber(r,['chains','observed_chains']);const draws=diagnosticNumber(r,['draws_per_chain','observed_draws_per_chain']);if(chains!==null)card('Recorded chains',String(chains));if(draws!==null)card('Draws per chain',number.format(draws));}
 for(const spec of diagnosticSpecs.slice(0,5)){const values=rows.map(r=>diagnosticNumber(r,spec.keys)).filter(v=>v!==null);if(!values.length)continue;const value=spec.higherBad?Math.max(...values):Math.min(...values);card(spec.id==='divergences'&&rows.length>1?'Maximum divergences in one fit':spec.label,number.format(value),spec.id==='rhat'?value>1.01:spec.id==='divergences'?value>0:false);}
 const predictiveFlags=rows.filter(r=>isTrue(r.flag)||isTrue(r.residual_dispersion_outside)||isTrue(r.studentized_tail_outside)||isTrue(r.flag_upper)||isTrue(r.review_flag_p_le_0_025)).length;
 if(rows.some(r=>['flag','residual_dispersion_outside','flag_upper','review_flag_p_le_0_025'].some(k=>k in r)))card('Rows with a recorded predictive flag',String(predictiveFlags),predictiveFlags>0);
 activeDiagnosticSpecs=diagnosticSpecs.filter(s=>rows.some(r=>diagnosticNumber(r,s.keys)!==null));const old=$('diagnostic-metric').value;
 options($('diagnostic-metric'),activeDiagnosticSpecs.map(s=>[s.id,s.label]),activeDiagnosticSpecs.some(s=>s.id===old)?old:activeDiagnosticSpecs[0]?.id);
 $('diagnostic-metric-label').hidden=!activeDiagnosticSpecs.length;$('chain-note').hidden=!activeDiagnosticSpecs.some(s=>['rhat','bulk','tail','bfmi','divergences'].includes(s.id));
 renderDiagnosticChart();
}
function renderDiagnosticChart(){
 const spec=activeDiagnosticSpecs.find(s=>s.id===$('diagnostic-metric').value);const root=$('diagnostic-chart');root.replaceChildren();diagnosticSVG='';$('diagnostic-svg').hidden=true;
 if(!spec){$('diagnostic-explanation').textContent='Review the recorded flags and full table below. No compatible quantitative diagnostic is available for this selection.';return;}
 let points=state.filtered.map((r,i)=>({r,i,value:diagnosticNumber(r,spec.keys)})).filter(p=>p.value!==null);
 if(spec.id==='ppc'){
  const checks=new Set(points.map(p=>p.r.check||p.r.domain||''));if(checks.size>1){$('diagnostic-explanation').textContent='Select one predictive check or domain above to compare observed values with the corresponding predictive interval.';return;}
  for(const p of points){p.low=diagnosticNumber(p.r,['replicated_95_lower','replicated_q025']);p.high=diagnosticNumber(p.r,['replicated_95_upper','replicated_q975']);p.outside=p.low!==null&&p.high!==null&&(p.value<p.low||p.value>p.high);}
  points.sort((a,b)=>Number(b.outside)-Number(a.outside));
 }else points.sort((a,b)=>spec.higherBad?b.value-a.value:a.value-b.value);
 const total=points.length;points=points.slice(0,40);if(!total)return;
 $('diagnostic-explanation').textContent=spec.note+' '+(total>40?'Showing 40 of '+total+' rows, ordered '+(spec.id==='ppc'?'with values outside the saved interval first.':spec.higherBad?'highest first.':'lowest first.')+' Every row remains in the table and CSV.':'All '+total+' summary rows shown.');
 const width=860,left=330,right=40,top=42,step=29,height=top+points.length*step+65;
 const vals=points.flatMap(p=>[p.value,p.low,p.high]).filter(v=>v!==null&&v!==undefined);if(spec.reference!==undefined)vals.push(spec.reference);
 let min=spec.id==='rhat'?Math.min(.99,...vals):Math.min(0,...vals),max=Math.max(...vals);if(max===min)max=min+1;const pad=(max-min)*.04;max+=pad;if(min<0)min-=pad;
 const x=v=>left+(v-min)/(max-min)*(width-left-right);
 const ns='http://www.w3.org/2000/svg',svg=document.createElementNS(ns,'svg');svg.setAttribute('viewBox',`0 0 ${width} ${height}`);svg.setAttribute('role','img');svg.setAttribute('aria-label',spec.label+' by saved family or fit');svg.setAttribute('xmlns',ns);
 const add=(name,attrs,text)=>{const n=document.createElementNS(ns,name);for(const[k,v]of Object.entries(attrs))n.setAttribute(k,v);if(text!==undefined)n.textContent=text;svg.append(n);return n;};
 add('rect',{width,height,fill:'white'});add('text',{x:14,y:20,'font-size':13,'font-family':'Arial',fill:'#1F1F1F'},spec.label);
 for(let i=0;i<=4;i++){const value=min+(max-min)*i/4,xx=x(value);add('line',{x1:xx,x2:xx,y1:top-10,y2:height-45,stroke:'#e5e8e8'});add('text',{x:xx,y:height-23,'text-anchor':'middle','font-family':'Arial','font-size':11,fill:'#6F7378'},number.format(value));}
 if(spec.reference!==undefined)add('line',{x1:x(spec.reference),x2:x(spec.reference),y1:top-12,y2:height-45,stroke:'#6F7378','stroke-dasharray':'5 4'});
 points.forEach((p,i)=>{const yy=top+i*step,label=human(p.r.parameter_family||programmeLabel(p.r)||p.r.key||p.r.global_feature||p.r.global_celltype||p.r.celltype||p.r.global_celltype||'Run summary');const t=add('text',{x:left-12,y:yy+4,'text-anchor':'end','font-size':11,'font-family':'Arial',fill:'#1F1F1F'},label.length>46?label.slice(0,43)+'…':label);const title=document.createElementNS(ns,'title');title.textContent=label+' = '+p.value;t.append(title);if(spec.id==='ppc'&&p.low!==null&&p.high!==null)add('line',{x1:x(p.low),x2:x(p.high),y1:yy,y2:yy,stroke:'#2C5AA0','stroke-width':3});const circle=add('circle',{cx:x(p.value),cy:yy,r:4,fill:spec.id==='ppc'||(spec.id==='rhat'&&p.value>1.01)||(spec.id==='divergences'&&p.value>0)?'#D81B60':'#0E7C7B'});const ct=document.createElementNS(ns,'title');ct.textContent=String(p.value);circle.append(ct);});
 root.append(svg);diagnosticSVG=new XMLSerializer().serializeToString(svg);$('diagnostic-svg').hidden=false;
}
$('diagnostic-svg').onclick=()=>save(diagnosticSVG,'atlas_'+$('diagnostic-metric').value+'.svg','image/svg+xml');

$('dataset').onchange=loadDataset;document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>setMode(b.dataset.mode));$('compartment').onchange=$('bmi-model').onchange=()=>changeSection(state.section);$('collection-search').oninput=()=>changeSection(state.section);$('diagnostic-metric').onchange=renderDiagnosticChart;$('search').oninput=applyFilters;$('include-failed').onchange=applyFilters;$('reset').onclick=()=>{$('search').value='';$('include-failed').checked=state.dataset?.kind==='diagnostics';buildFacets();applyFilters();};$('prev').onclick=()=>{state.page--;drawTable();};$('next').onclick=()=>{state.page++;drawTable();};$('view-table').onclick=()=>view('table');$('view-plot').onclick=()=>view('plot');$('plot-type').onchange=()=>{clearFigure();plotControls();};$('draw').onclick=drawPlot;
$('download-json').onclick=()=>{const result={};for(const r of state.filtered){result[r.cell_type]??={};result[r.cell_type][r.signature]=r.genes;}save(JSON.stringify(result,null,2),'signature_selection.json','application/json');};
$('download').onclick=()=>save(filteredCSV(state.filtered),state.dataset.id.replaceAll('/','_')+'.csv','text/csv;charset=utf-8');$('svg').onclick=()=>save(state.figure.svg,'atlas_figure.svg','image/svg+xml');$('png').onclick=()=>{const b=Uint8Array.from(atob(state.figure.png),c=>c.charCodeAt(0));save(new Blob([b],{type:'image/png'}),'atlas_figure.png');};
for(const [i,[id,name]]of sections.entries()){const b=el('button',undefined,{role:'tab','aria-selected':id===state.section});b.dataset.section=id;b.append(el('span',String(i+1).padStart(2,'0'),{class:'num'}),el('span',name));b.onclick=()=>changeSection(id);$('sections').append(b);}
(async()=>{try{state.catalog=await api('atlas_web_datasets',{select:'id,section,title,kind,description,run_key,row_count,provisional',order:'id.asc',limit:200});if(!state.catalog.length){$('connection').textContent='Website ready · data release pending';$('dataset-title').textContent='Collections awaiting publication';status('The results have been prepared. Public access will open after the lab approves the data release.');$('search').disabled=true;$('reset').disabled=true;return;}$('connection').textContent=state.catalog.length+' collections · connected to the research data';const p=new URLSearchParams(location.hash.slice(1));const d=state.catalog.find(d=>d.id===p.get('dataset'));state.mode=['biology','reliability','advanced'].includes(p.get('mode'))?p.get('mode'):(d&&d.kind!=='effects'?'advanced':'biology');syncRunControls(d);updateModeUI();changeSection(d?.section||'rna',d?.id||'immune_coarse/effects');}catch(e){$('connection').textContent='Connection unavailable';$('dataset-title').textContent='Results temporarily unavailable';status(e.message,true);}})();
